service: appointment-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  environment:
    APPOINTMENT_TOPIC_ARN: arn:aws:sns:us-east-2:759799978288:APPOINTMENT_TOPIC
    APPOINTMENTS_TABLE: appointments
    RDS_HOST: appointment-db.c9ywiwkicl8m.us-east-2.rds.amazonaws.com
    RDS_USER: admin
    RDS_PASSWORD: adminawstest
    RDS_DB_NAME: appointments
  # vpc:
  #   securityGroupIds:
  #     - sg-067d7213d0187d6a8      # ID del security group que permita el acceso a RDS
  #   subnetIds:
  #     - subnet-00e62ff7c3f28a2c7  # Subnets de tu VPC que tengan acceso a RDS
  #     - subnet-023b7fbc009847ee0
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - sns:Publish
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - events:PutEvents
          Resource: "*"

custom:
  documentation:
    api:
      info:
        version: "1.0.0"
        title: "Appointment API"
        description: "API para agendamiento de citas médicas"
    models:
      - name: CreateAppointmentRequest
        contentType: "application/json"
        schema:
          type: object
          properties:
            insuredId:
              type: string
              example: "00123"
            scheduleId:
              type: integer
              example: 100
            countryISO:
              type: string
              enum: [PE, CL]
          required: [insuredId, scheduleId, countryISO]

      - name: AppointmentResponse
        contentType: "application/json"
        schema:
          type: object
          properties:
            appointmentId:
              type: string
            status:
              type: string
              example: "pending"
plugins:
  - serverless-openapi-documenter

functions:
  postAppointment:
    handler: src/interfaces/handlers/postAppointment.handler
    events:
      - http:
          path: appointments
          method: post
    documentation:
      summary: "Crear un appointment"
      description: "Registra un nuevo appointment y lo envía a SNS"
      requestModels:
        "application/json": CreateAppointmentRequest
      responseModels:
        "application/json": AppointmentResponse

  getAppointments:
    handler: src/interfaces/handlers/getAppointments.handler
    events:
      - http:
          path: appointments/{insuredId}
          method: get
    documentation:
      summary: "Listar appointments"
      description: "Obtiene los appointments de un asegurado"
      pathParams:
        - name: insuredId
          description: "Código del asegurado"
          required: true
          type: string
      responseModels:
        "application/json": AppointmentResponse

  appointment_pe:
    handler: src/interfaces/handlers/appointment_pe.handler
    timeout: 30
    events:
      - sqs:
          arn: 
            Fn::GetAtt: [SQSPE, Arn]

resources:
  Resources:
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointments
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    SQSPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_PE

    SQSCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CL

    SNSSubscriptionPE:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: arn:aws:sns:us-east-2:759799978288:APPOINTMENT_TOPIC
        Endpoint: !GetAtt SQSPE.Arn
        FilterPolicy:
          countryISO:
            - PE

    SNSSubscriptionCL:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: arn:aws:sns:us-east-2:759799978288:APPOINTMENT_TOPIC
        Endpoint: !GetAtt SQSCL.Arn
        FilterPolicy:
          countryISO:
            - CL

    SQSPolicyPE:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSPE
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource: !GetAtt SQSPE.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: arn:aws:sns:us-east-2:759799978288:APPOINTMENT_TOPIC

    SQSPolicyCL:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSCL
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "sqs:SendMessage"
              Resource: !GetAtt SQSCL.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: arn:aws:sns:us-east-2:759799978288:APPOINTMENT_TOPIC
        
    AppointmentConfirmedLogRule:
      Type: AWS::Events::Rule
      Properties:
        Name: appointmentConfirmedRule
        EventPattern:
          source:
            - "appointments.pe"
          detail-type:
            - "appointmentConfirmed"
        Targets:
          - Arn: !GetAtt AppointmentLogGroup.Arn
            Id: "LogTarget"

    AppointmentLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/events/appointmentConfirmed
        RetentionInDays: 3